/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as MinhaListaRouteImport } from './routes/minha-lista'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PontosRouteImport } from './routes/pontos'
import { Route as RecomendacoesRouteImport } from './routes/recomendacoes'
import { Route as VerificarRouteImport } from './routes/verificar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaListaRoute = MinhaListaRouteImport.update({
  id: '/minha-lista',
  path: '/minha-lista',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PontosRoute = PontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendacoesRoute = RecomendacoesRouteImport.update({
  id: '/recomendacoes',
  path: '/recomendacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jogos': typeof JogosRoute
  '/lista': typeof ListaRoute
  '/mercado': typeof MercadoRoute
  '/minha-lista': typeof MinhaListaRoute
  '/perfil': typeof PerfilRoute
  '/pontos': typeof PontosRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/verificar': typeof VerificarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jogos': typeof JogosRoute
  '/lista': typeof ListaRoute
  '/mercado': typeof MercadoRoute
  '/minha-lista': typeof MinhaListaRoute
  '/perfil': typeof PerfilRoute
  '/pontos': typeof PontosRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/verificar': typeof VerificarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jogos': typeof JogosRoute
  '/lista': typeof ListaRoute
  '/mercado': typeof MercadoRoute
  '/minha-lista': typeof MinhaListaRoute
  '/perfil': typeof PerfilRoute
  '/pontos': typeof PontosRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/verificar': typeof VerificarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jogos'
    | '/lista'
    | '/mercado'
    | '/minha-lista'
    | '/perfil'
    | '/pontos'
    | '/recomendacoes'
    | '/verificar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jogos'
    | '/lista'
    | '/mercado'
    | '/minha-lista'
    | '/perfil'
    | '/pontos'
    | '/recomendacoes'
    | '/verificar'
  id:
    | '__root__'
    | '/'
    | '/jogos'
    | '/lista'
    | '/mercado'
    | '/minha-lista'
    | '/perfil'
    | '/pontos'
    | '/recomendacoes'
    | '/verificar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JogosRoute: typeof JogosRoute
  ListaRoute: typeof ListaRoute
  MercadoRoute: typeof MercadoRoute
  MinhaListaRoute: typeof MinhaListaRoute
  PerfilRoute: typeof PerfilRoute
  PontosRoute: typeof PontosRoute
  RecomendacoesRoute: typeof RecomendacoesRoute
  VerificarRoute: typeof VerificarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-lista': {
      id: '/minha-lista'
      path: '/minha-lista'
      fullPath: '/minha-lista'
      preLoaderRoute: typeof MinhaListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pontos': {
      id: '/pontos'
      path: '/pontos'
      fullPath: '/pontos'
      preLoaderRoute: typeof PontosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendacoes': {
      id: '/recomendacoes'
      path: '/recomendacoes'
      fullPath: '/recomendacoes'
      preLoaderRoute: typeof RecomendacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JogosRoute: JogosRoute,
  ListaRoute: ListaRoute,
  MercadoRoute: MercadoRoute,
  MinhaListaRoute: MinhaListaRoute,
  PerfilRoute: PerfilRoute,
  PontosRoute: PontosRoute,
  RecomendacoesRoute: RecomendacoesRoute,
  VerificarRoute: VerificarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
